-- Oracle Attendance Tracking Database Schema
-- Converted from n8n workflows to Oracle Database
-- Date: 2026-02-19

-- =====================================================
-- SEQUENCES (Auto-increment IDs in Oracle)
-- =====================================================
CREATE SEQUENCE SEQ_STUDENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLASS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ATTENDANCE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PATTERN_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ENROLLMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================================
-- MAIN TABLES
-- =====================================================

-- Students table (with day_check, absence_count, late_count from workflows)
CREATE TABLE STUDENTS (
  STUDENT_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR2(100) NOT NULL,
  LAST_NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(255) UNIQUE,
  DAY_CHECK NUMBER(1) DEFAULT 0 NOT NULL CHECK (DAY_CHECK IN (0, 1)),
  ABSENCE_COUNT NUMBER DEFAULT 0 NOT NULL,
  LATE_COUNT NUMBER DEFAULT 0 NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Classes table
CREATE TABLE CLASSES (
  CLASS_ID NUMBER PRIMARY KEY,
  CLASS_NAME VARCHAR2(200) NOT NULL,
  SEMESTER VARCHAR2(50) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Student-Classes enrollment (many-to-many)
CREATE TABLE STUDENT_CLASSES (
  ENROLLMENT_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  CLASS_ID NUMBER NOT NULL,
  ENROLLED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_SC_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SC_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID) ON DELETE CASCADE,
  CONSTRAINT UQ_STUDENT_CLASS UNIQUE (STUDENT_ID, CLASS_ID)
);

-- Attendance table
CREATE TABLE ATTENDANCE (
  ATTENDANCE_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  CLASS_ID NUMBER,
  SESSION_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('PRESENT', 'ABSENT', 'LATE')),
  MINUTES_LATE NUMBER DEFAULT 0,
  REASON VARCHAR2(500),
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_ATT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_ATT_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID) ON DELETE SET NULL
);

-- Alerts table
CREATE TABLE ALERTS (
  ALERT_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  ALERT_TYPE VARCHAR2(50) NOT NULL,
  MESSAGE VARCHAR2(1000) NOT NULL,
  THRESHOLD NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (STATUS IN ('ACTIVE', 'RESOLVED', 'DISMISSED')),
  CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
  RESOLVED_AT TIMESTAMP,
  CONSTRAINT FK_ALERT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE
);

-- Anomaly Patterns table
CREATE TABLE ANOMALY_PATTERNS (
  PATTERN_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  PATTERN_TYPE VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(1000) NOT NULL,
  SEVERITY VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (SEVERITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  DETECTION_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  IS_RESOLVED NUMBER(1) DEFAULT 0 CHECK (IS_RESOLVED IN (0, 1)),
  RESOLVED_DATE TIMESTAMP,
  CONSTRAINT FK_PATTERN_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE
);

-- Alert Thresholds table (configurable alert thresholds)
CREATE TABLE ALERT_THRESHOLDS (
  THRESHOLD_ID NUMBER PRIMARY KEY,
  THRESHOLD_TYPE VARCHAR2(50) NOT NULL UNIQUE,
  THRESHOLD_VALUE NUMBER NOT NULL,
  PERIOD VARCHAR2(20) DEFAULT 'MONTHLY' CHECK (PERIOD IN ('DAILY', 'WEEKLY', 'MONTHLY', 'SEMESTER')),
  DESCRIPTION VARCHAR2(500),
  IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================
CREATE INDEX IDX_STUDENTS_EMAIL ON STUDENTS(EMAIL);
CREATE INDEX IDX_ATT_STUDENT ON ATTENDANCE(STUDENT_ID);
CREATE INDEX IDX_ATT_DATE ON ATTENDANCE(SESSION_DATE);
CREATE INDEX IDX_ATT_STATUS ON ATTENDANCE(STATUS);
CREATE INDEX IDX_ATT_COMPOSITE ON ATTENDANCE(STUDENT_ID, SESSION_DATE);
CREATE INDEX IDX_ALERTS_STUDENT ON ALERTS(STUDENT_ID);
CREATE INDEX IDX_ALERTS_STATUS ON ALERTS(STATUS);
CREATE INDEX IDX_ALERTS_CREATED ON ALERTS(CREATED_AT);
CREATE INDEX IDX_PATTERNS_STUDENT ON ANOMALY_PATTERNS(STUDENT_ID);
CREATE INDEX IDX_PATTERNS_DATE ON ANOMALY_PATTERNS(DETECTION_DATE);
CREATE INDEX IDX_SC_STUDENT ON STUDENT_CLASSES(STUDENT_ID);
CREATE INDEX IDX_SC_CLASS ON STUDENT_CLASSES(CLASS_ID);

-- =====================================================
-- TRIGGERS FOR AUTO-INCREMENT
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_STUDENTS_ID
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
  IF :NEW.STUDENT_ID IS NULL THEN
    SELECT SEQ_STUDENT_ID.NEXTVAL INTO :NEW.STUDENT_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLASSES_ID
BEFORE INSERT ON CLASSES
FOR EACH ROW
BEGIN
  IF :NEW.CLASS_ID IS NULL THEN
    SELECT SEQ_CLASS_ID.NEXTVAL INTO :NEW.CLASS_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ATTENDANCE_ID
BEFORE INSERT ON ATTENDANCE
FOR EACH ROW
BEGIN
  IF :NEW.ATTENDANCE_ID IS NULL THEN
    SELECT SEQ_ATTENDANCE_ID.NEXTVAL INTO :NEW.ATTENDANCE_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTS_ID
BEFORE INSERT ON ALERTS
FOR EACH ROW
BEGIN
  IF :NEW.ALERT_ID IS NULL THEN
    SELECT SEQ_ALERT_ID.NEXTVAL INTO :NEW.ALERT_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PATTERNS_ID
BEFORE INSERT ON ANOMALY_PATTERNS
FOR EACH ROW
BEGIN
  IF :NEW.PATTERN_ID IS NULL THEN
    SELECT SEQ_PATTERN_ID.NEXTVAL INTO :NEW.PATTERN_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ENROLLMENTS_ID
BEFORE INSERT ON STUDENT_CLASSES
FOR EACH ROW
BEGIN
  IF :NEW.ENROLLMENT_ID IS NULL THEN
    SELECT SEQ_ENROLLMENT_ID.NEXTVAL INTO :NEW.ENROLLMENT_ID FROM DUAL;
  END IF;
END;
/

-- =====================================================
-- AUTO-INCREMENT TRIGGER FOR ALERT_THRESHOLDS
-- =====================================================
CREATE SEQUENCE SEQ_THRESHOLD_ID START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_THRESHOLDS_ID
BEFORE INSERT ON ALERT_THRESHOLDS
FOR EACH ROW
BEGIN
  IF :NEW.THRESHOLD_ID IS NULL THEN
    SELECT SEQ_THRESHOLD_ID.NEXTVAL INTO :NEW.THRESHOLD_ID FROM DUAL;
  END IF;
END;
/

-- =====================================================
-- BUSINESS LOGIC TRIGGERS (Project Requirement: Trigger-based automation)
-- =====================================================

-- Trigger 1: Auto-create alert when absence threshold exceeded
CREATE OR REPLACE TRIGGER TRG_ABSENCE_ALERT
AFTER UPDATE OF ABSENCE_COUNT ON STUDENTS
FOR EACH ROW
DECLARE
    v_threshold NUMBER;
    v_alert_exists NUMBER;
BEGIN
    SELECT THRESHOLD_VALUE INTO v_threshold
    FROM ALERT_THRESHOLDS
    WHERE THRESHOLD_TYPE = 'ABSENCE_MONTHLY' AND IS_ACTIVE = 1;
    
    IF :NEW.ABSENCE_COUNT >= v_threshold AND :OLD.ABSENCE_COUNT < v_threshold THEN
        SELECT COUNT(*) INTO v_alert_exists
        FROM ALERTS
        WHERE STUDENT_ID = :NEW.STUDENT_ID 
        AND ALERT_TYPE = 'ABSENCE_THRESHOLD'
        AND STATUS = 'ACTIVE';
        
        IF v_alert_exists = 0 THEN
            INSERT INTO ALERTS (STUDENT_ID, ALERT_TYPE, THRESHOLD, MESSAGE, STATUS)
            VALUES (
                :NEW.STUDENT_ID, 
                'ABSENCE_THRESHOLD', 
                v_threshold,
                'Student ' || :NEW.FIRST_NAME || ' ' || :NEW.LAST_NAME || 
                ' has exceeded absence threshold (' || :NEW.ABSENCE_COUNT || ' absences)',
                'ACTIVE'
            );
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

-- Trigger 2: Auto-create alert for excessive lateness
CREATE OR REPLACE TRIGGER TRG_LATE_ALERT
AFTER UPDATE OF LATE_COUNT ON STUDENTS
FOR EACH ROW
DECLARE
    v_threshold NUMBER;
    v_alert_exists NUMBER;
BEGIN
    SELECT THRESHOLD_VALUE INTO v_threshold
    FROM ALERT_THRESHOLDS
    WHERE THRESHOLD_TYPE = 'LATE_MONTHLY' AND IS_ACTIVE = 1;
    
    IF :NEW.LATE_COUNT >= v_threshold AND :OLD.LATE_COUNT < v_threshold THEN
        SELECT COUNT(*) INTO v_alert_exists
        FROM ALERTS
        WHERE STUDENT_ID = :NEW.STUDENT_ID 
        AND ALERT_TYPE = 'LATE_THRESHOLD'
        AND STATUS = 'ACTIVE';
        
        IF v_alert_exists = 0 THEN
            INSERT INTO ALERTS (STUDENT_ID, ALERT_TYPE, THRESHOLD, MESSAGE, STATUS)
            VALUES (
                :NEW.STUDENT_ID, 
                'LATE_THRESHOLD', 
                v_threshold,
                'Student has been late ' || :NEW.LATE_COUNT || ' times',
                'ACTIVE'
            );
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

-- Trigger 3: Detect consecutive absences anomaly
CREATE OR REPLACE TRIGGER TRG_CONSECUTIVE_ABSENCES
AFTER INSERT ON ATTENDANCE
FOR EACH ROW
DECLARE
    v_consecutive_count NUMBER;
    v_threshold NUMBER;
BEGIN
    IF :NEW.STATUS = 'ABSENT' THEN
        SELECT THRESHOLD_VALUE INTO v_threshold
        FROM ALERT_THRESHOLDS
        WHERE THRESHOLD_TYPE = 'CONSECUTIVE_ABSENCES' AND IS_ACTIVE = 1;
        
        SELECT COUNT(*) INTO v_consecutive_count
        FROM (
            SELECT STATUS, SESSION_DATE
            FROM ATTENDANCE
            WHERE STUDENT_ID = :NEW.STUDENT_ID
            AND SESSION_DATE <= :NEW.SESSION_DATE
            ORDER BY SESSION_DATE DESC
            FETCH FIRST 3 ROWS ONLY
        )
        WHERE STATUS = 'ABSENT';
        
        IF v_consecutive_count >= v_threshold THEN
            INSERT INTO ANOMALY_PATTERNS (
                STUDENT_ID, 
                PATTERN_TYPE, 
                DESCRIPTION, 
                SEVERITY
            )
            VALUES (
                :NEW.STUDENT_ID,
                'CONSECUTIVE_ABSENCES',
                v_consecutive_count || ' consecutive absences detected',
                'HIGH'
            );
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

-- Trigger 4: Validate attendance data before insert
CREATE OR REPLACE TRIGGER TRG_ATTENDANCE_VALIDATION
BEFORE INSERT ON ATTENDANCE
FOR EACH ROW
DECLARE
    v_existing_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existing_count
    FROM ATTENDANCE
    WHERE STUDENT_ID = :NEW.STUDENT_ID
    AND TRUNC(SESSION_DATE) = TRUNC(:NEW.SESSION_DATE)
    AND (:NEW.CLASS_ID IS NULL OR CLASS_ID = :NEW.CLASS_ID);
    
    IF v_existing_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'Attendance already recorded for this student on this date');
    END IF;
    
    IF :NEW.STATUS = 'LATE' AND (:NEW.MINUTES_LATE IS NULL OR :NEW.MINUTES_LATE <= 0) THEN
        RAISE_APPLICATION_ERROR(-20002, 
            'Minutes late must be specified and greater than 0 for LATE status');
    END IF;
    
    IF :NEW.STATUS = 'ABSENT' AND :NEW.REASON IS NULL THEN
        :NEW.REASON := 'No reason provided';
    END IF;
END;
/

-- Trigger 5: Auto-update timestamps on STUDENTS
CREATE OR REPLACE TRIGGER TRG_STUDENTS_UPDATE_TIME
BEFORE UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := SYSDATE;
END;
/

-- =====================================================
-- DEFAULT ALERT THRESHOLDS
-- =====================================================
INSERT INTO ALERT_THRESHOLDS (THRESHOLD_TYPE, THRESHOLD_VALUE, PERIOD, DESCRIPTION)
VALUES ('ABSENCE_MONTHLY', 5, 'MONTHLY', 'Alert when student has 5+ absences in a month');

INSERT INTO ALERT_THRESHOLDS (THRESHOLD_TYPE, THRESHOLD_VALUE, PERIOD, DESCRIPTION)
VALUES ('LATE_MONTHLY', 10, 'MONTHLY', 'Alert when student is late 10+ times in a month');

INSERT INTO ALERT_THRESHOLDS (THRESHOLD_TYPE, THRESHOLD_VALUE, PERIOD, DESCRIPTION)
VALUES ('CONSECUTIVE_ABSENCES', 3, 'DAILY', 'Alert when student has 3 consecutive absences');

COMMIT;

-- =====================================================
-- SAMPLE DATA
-- =====================================================
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('John', 'Doe', 'john.doe@example.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Jane', 'Smith', 'jane.smith@example.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bob', 'Johnson', 'bob.johnson@example.com');

INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Introduction to Computer Science', 'Fall 2025');
INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Data Structures', 'Fall 2025');
INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Web Development', 'Fall 2025');

COMMIT;
