-- Oracle Attendance Tracking Database Schema
-- Converted from n8n workflows to Oracle Database
-- Date: 2026-02-19

-- =====================================================
-- SEQUENCES (Auto-increment IDs in Oracle)
-- =====================================================
CREATE SEQUENCE SEQ_STUDENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLASS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ATTENDANCE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PATTERN_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ENROLLMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================================
-- MAIN TABLES
-- =====================================================

-- Students table (with day_check, absence_count, late_count from workflows)
CREATE TABLE STUDENTS (
  STUDENT_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR2(100) NOT NULL,
  LAST_NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(255) UNIQUE,
  DAY_CHECK NUMBER(1) DEFAULT 0 NOT NULL CHECK (DAY_CHECK IN (0, 1)),
  ABSENCE_COUNT NUMBER DEFAULT 0 NOT NULL,
  LATE_COUNT NUMBER DEFAULT 0 NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Classes table
CREATE TABLE CLASSES (
  CLASS_ID NUMBER PRIMARY KEY,
  CLASS_NAME VARCHAR2(200) NOT NULL,
  SEMESTER VARCHAR2(50) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Student-Classes enrollment (many-to-many)
CREATE TABLE STUDENT_CLASSES (
  ENROLLMENT_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  CLASS_ID NUMBER NOT NULL,
  ENROLLED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_SC_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SC_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID) ON DELETE CASCADE,
  CONSTRAINT UQ_STUDENT_CLASS UNIQUE (STUDENT_ID, CLASS_ID)
);

-- Attendance table
CREATE TABLE ATTENDANCE (
  ATTENDANCE_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  CLASS_ID NUMBER,
  SESSION_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('PRESENT', 'ABSENT', 'LATE')),
  MINUTES_LATE NUMBER DEFAULT 0,
  REASON VARCHAR2(500),
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_ATT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_ATT_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID) ON DELETE SET NULL
);

-- Alerts table
CREATE TABLE ALERTS (
  ALERT_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  ALERT_TYPE VARCHAR2(50) NOT NULL,
  MESSAGE VARCHAR2(1000) NOT NULL,
  THRESHOLD NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (STATUS IN ('ACTIVE', 'RESOLVED', 'DISMISSED')),
  CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
  RESOLVED_AT TIMESTAMP,
  CONSTRAINT FK_ALERT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE
);

-- Anomaly Patterns table
CREATE TABLE ANOMALY_PATTERNS (
  PATTERN_ID NUMBER PRIMARY KEY,
  STUDENT_ID NUMBER NOT NULL,
  PATTERN_TYPE VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(1000) NOT NULL,
  SEVERITY VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (SEVERITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  DETECTION_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
  IS_RESOLVED NUMBER(1) DEFAULT 0 CHECK (IS_RESOLVED IN (0, 1)),
  CONSTRAINT FK_PATTERN_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================
CREATE INDEX IDX_STUDENTS_EMAIL ON STUDENTS(EMAIL);
CREATE INDEX IDX_ATT_STUDENT ON ATTENDANCE(STUDENT_ID);
CREATE INDEX IDX_ATT_DATE ON ATTENDANCE(SESSION_DATE);
CREATE INDEX IDX_ATT_STATUS ON ATTENDANCE(STATUS);
CREATE INDEX IDX_ATT_COMPOSITE ON ATTENDANCE(STUDENT_ID, SESSION_DATE);
CREATE INDEX IDX_ALERTS_STUDENT ON ALERTS(STUDENT_ID);
CREATE INDEX IDX_ALERTS_STATUS ON ALERTS(STATUS);
CREATE INDEX IDX_ALERTS_CREATED ON ALERTS(CREATED_AT);
CREATE INDEX IDX_PATTERNS_STUDENT ON ANOMALY_PATTERNS(STUDENT_ID);
CREATE INDEX IDX_PATTERNS_DATE ON ANOMALY_PATTERNS(DETECTION_DATE);
CREATE INDEX IDX_SC_STUDENT ON STUDENT_CLASSES(STUDENT_ID);
CREATE INDEX IDX_SC_CLASS ON STUDENT_CLASSES(CLASS_ID);

-- =====================================================
-- TRIGGERS FOR AUTO-INCREMENT
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_STUDENTS_ID
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
  IF :NEW.STUDENT_ID IS NULL THEN
    SELECT SEQ_STUDENT_ID.NEXTVAL INTO :NEW.STUDENT_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLASSES_ID
BEFORE INSERT ON CLASSES
FOR EACH ROW
BEGIN
  IF :NEW.CLASS_ID IS NULL THEN
    SELECT SEQ_CLASS_ID.NEXTVAL INTO :NEW.CLASS_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ATTENDANCE_ID
BEFORE INSERT ON ATTENDANCE
FOR EACH ROW
BEGIN
  IF :NEW.ATTENDANCE_ID IS NULL THEN
    SELECT SEQ_ATTENDANCE_ID.NEXTVAL INTO :NEW.ATTENDANCE_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTS_ID
BEFORE INSERT ON ALERTS
FOR EACH ROW
BEGIN
  IF :NEW.ALERT_ID IS NULL THEN
    SELECT SEQ_ALERT_ID.NEXTVAL INTO :NEW.ALERT_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PATTERNS_ID
BEFORE INSERT ON ANOMALY_PATTERNS
FOR EACH ROW
BEGIN
  IF :NEW.PATTERN_ID IS NULL THEN
    SELECT SEQ_PATTERN_ID.NEXTVAL INTO :NEW.PATTERN_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ENROLLMENTS_ID
BEFORE INSERT ON STUDENT_CLASSES
FOR EACH ROW
BEGIN
  IF :NEW.ENROLLMENT_ID IS NULL THEN
    SELECT SEQ_ENROLLMENT_ID.NEXTVAL INTO :NEW.ENROLLMENT_ID FROM DUAL;
  END IF;
END;
/

-- =====================================================
-- SAMPLE DATA
-- =====================================================
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('John', 'Doe', 'john.doe@example.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Jane', 'Smith', 'jane.smith@example.com');
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bob', 'Johnson', 'bob.johnson@example.com');

INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Introduction to Computer Science', 'Fall 2025');
INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Data Structures', 'Fall 2025');
INSERT INTO CLASSES (CLASS_NAME, SEMESTER) VALUES ('Web Development', 'Fall 2025');

COMMIT;
